# Generated by Django 4.0.2 on 2022-03-09 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockdata',
            name='request_data',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='mockdata',
            name='data',
            field=models.JSONField(null=True),
        ),
    ]
