# Generated by Django 4.0.2 on 2022-03-09 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mocks', '0002_mockdata_request_data_alter_mockdata_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mockdata',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mockdata',
            name='request_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
