# Generated by Django 4.0.2 on 2022-03-12 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mocks', '0003_alter_mockdata_data_alter_mockdata_request_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mockdata',
            name='data',
            field=models.JSONField(blank=True, null=True, verbose_name='Response data property'),
        ),
    ]
